namespace Shiftv.Contracts.Domain.Shows
{
    public interface IEpisodesProgress
    {
        bool? Episode1 { get; set; }
        bool? Episode2 { get; set; }
        bool? Episode3 { get; set; }
        bool? Episode4 { get; set; }
        bool? Episode5 { get; set; }
        bool? Episode6 { get; set; }
        bool? Episode7 { get; set; }
        bool? Episode8 { get; set; }
        bool? Episode9 { get; set; }
        bool? Episode10 { get; set; }
        bool? Episode11 { get; set; }
        bool? Episode12 { get; set; }
        bool? Episode13 { get; set; }
        bool? Episode14 { get; set; }
        bool? Episode15 { get; set; }
        bool? Episode16 { get; set; }
        bool? Episode17 { get; set; }
        bool? Episode18 { get; set; }
        bool? Episode19 { get; set; }
        bool? Episode20 { get; set; }
        bool? Episode21 { get; set; }
        bool? Episode22 { get; set; }
        bool? Episode23 { get; set; }
        bool? Episode24 { get; set; }
        bool? Episode25 { get; set; }
        bool? Episode26 { get; set; }
        bool? Episode27 { get; set; }
        bool? Episode28 { get; set; }
        bool? Episode29 { get; set; }
        bool? Episode30 { get; set; }
        bool? Episode31 { get; set; }
        bool? Episode32 { get; set; }
        bool? Episode33 { get; set; }
        bool? Episode34 { get; set; }
        bool? Episode35 { get; set; }
        bool? Episode36 { get; set; }
        bool? Episode37 { get; set; }
        bool? Episode38 { get; set; }
        bool? Episode39 { get; set; }
        bool? Episode40 { get; set; }
        bool? Episode41 { get; set; }
        bool? Episode42 { get; set; }
        bool? Episode43 { get; set; }
        bool? Episode44 { get; set; }
        bool? Episode45 { get; set; }
        bool? Episode46 { get; set; }
        bool? Episode47 { get; set; }
        bool? Episode48 { get; set; }
        bool? Episode49 { get; set; }
        bool? Episode50 { get; set; }
        bool? Episode51 { get; set; }
        bool? Episode52 { get; set; }
        bool? Episode53 { get; set; }
        bool? Episode54 { get; set; }
        bool? Episode55 { get; set; }
        bool? Episode56 { get; set; }
        bool? Episode57 { get; set; }
        bool? Episode58 { get; set; }
        bool? Episode59 { get; set; }
        bool? Episode60 { get; set; }
        bool? Episode61 { get; set; }
        bool? Episode62 { get; set; }
        bool? Episode63 { get; set; }
        bool? Episode64 { get; set; }
        bool? Episode65 { get; set; }
        bool? Episode66 { get; set; }
        bool? Episode67 { get; set; }
        bool? Episode68 { get; set; }
        bool? Episode69 { get; set; }
        bool? Episode70 { get; set; }
        bool? Episode71 { get; set; }
        bool? Episode72 { get; set; }
        bool? Episode73 { get; set; }
        bool? Episode74 { get; set; }
        bool? Episode75 { get; set; }
        bool? Episode76 { get; set; }
        bool? Episode77 { get; set; }
        bool? Episode78 { get; set; }
        bool? Episode79 { get; set; }
        bool? Episode80 { get; set; }
        bool? Episode81 { get; set; }
        bool? Episode82 { get; set; }
        bool? Episode83 { get; set; }
        bool? Episode84 { get; set; }
        bool? Episode85 { get; set; }
        bool? Episode86 { get; set; }
        bool? Episode87 { get; set; }
        bool? Episode88 { get; set; }
        bool? Episode89 { get; set; }
        bool? Episode90 { get; set; }
        bool? Episode91 { get; set; }
        bool? Episode92 { get; set; }
        bool? Episode93 { get; set; }
        bool? Episode94 { get; set; }
        bool? Episode95 { get; set; }
        bool? Episode96 { get; set; }
        bool? Episode97 { get; set; }
        bool? Episode98 { get; set; }
        bool? Episode99 { get; set; }
        bool? Episode100 { get; set; }
    }
}