using Shiftv.Contracts.Domain.Shows;

namespace Shiftv.Core.Models.Shows
{
    class EpisodesProgress : IEpisodesProgress
    {
        public bool? Episode1 { get; set; }
        public bool? Episode2 { get; set; }
        public bool? Episode3 { get; set; }
        public bool? Episode4 { get; set; }
        public bool? Episode5 { get; set; }
        public bool? Episode6 { get; set; }
        public bool? Episode7 { get; set; }
        public bool? Episode8 { get; set; }
        public bool? Episode9 { get; set; }
        public bool? Episode10 { get; set; }
        public bool? Episode11 { get; set; }
        public bool? Episode12 { get; set; }
        public bool? Episode13 { get; set; }
        public bool? Episode14 { get; set; }
        public bool? Episode15 { get; set; }
        public bool? Episode16 { get; set; }
        public bool? Episode17 { get; set; }
        public bool? Episode18 { get; set; }
        public bool? Episode19 { get; set; }
        public bool? Episode20 { get; set; }
        public bool? Episode21 { get; set; }
        public bool? Episode22 { get; set; }
        public bool? Episode23 { get; set; }
        public bool? Episode24 { get; set; }
        public bool? Episode25 { get; set; }
        public bool? Episode26 { get; set; }
        public bool? Episode27 { get; set; }
        public bool? Episode28 { get; set; }
        public bool? Episode29 { get; set; }
        public bool? Episode30 { get; set; }
        public bool? Episode31 { get; set; }
        public bool? Episode32 { get; set; }
        public bool? Episode33 { get; set; }
        public bool? Episode34 { get; set; }
        public bool? Episode35 { get; set; }
        public bool? Episode36 { get; set; }
        public bool? Episode37 { get; set; }
        public bool? Episode38 { get; set; }
        public bool? Episode39 { get; set; }
        public bool? Episode40 { get; set; }
        public bool? Episode41 { get; set; }
        public bool? Episode42 { get; set; }
        public bool? Episode43 { get; set; }
        public bool? Episode44 { get; set; }
        public bool? Episode45 { get; set; }
        public bool? Episode46 { get; set; }
        public bool? Episode47 { get; set; }
        public bool? Episode48 { get; set; }
        public bool? Episode49 { get; set; }
        public bool? Episode50 { get; set; }
        public bool? Episode51 { get; set; }
        public bool? Episode52 { get; set; }
        public bool? Episode53 { get; set; }
        public bool? Episode54 { get; set; }
        public bool? Episode55 { get; set; }
        public bool? Episode56 { get; set; }
        public bool? Episode57 { get; set; }
        public bool? Episode58 { get; set; }
        public bool? Episode59 { get; set; }
        public bool? Episode60 { get; set; }
        public bool? Episode61 { get; set; }
        public bool? Episode62 { get; set; }
        public bool? Episode63 { get; set; }
        public bool? Episode64 { get; set; }
        public bool? Episode65 { get; set; }
        public bool? Episode66 { get; set; }
        public bool? Episode67 { get; set; }
        public bool? Episode68 { get; set; }
        public bool? Episode69 { get; set; }
        public bool? Episode70 { get; set; }
        public bool? Episode71 { get; set; }
        public bool? Episode72 { get; set; }
        public bool? Episode73 { get; set; }
        public bool? Episode74 { get; set; }
        public bool? Episode75 { get; set; }
        public bool? Episode76 { get; set; }
        public bool? Episode77 { get; set; }
        public bool? Episode78 { get; set; }
        public bool? Episode79 { get; set; }
        public bool? Episode80 { get; set; }
        public bool? Episode81 { get; set; }
        public bool? Episode82 { get; set; }
        public bool? Episode83 { get; set; }
        public bool? Episode84 { get; set; }
        public bool? Episode85 { get; set; }
        public bool? Episode86 { get; set; }
        public bool? Episode87 { get; set; }
        public bool? Episode88 { get; set; }
        public bool? Episode89 { get; set; }
        public bool? Episode90 { get; set; }
        public bool? Episode91 { get; set; }
        public bool? Episode92 { get; set; }
        public bool? Episode93 { get; set; }
        public bool? Episode94 { get; set; }
        public bool? Episode95 { get; set; }
        public bool? Episode96 { get; set; }
        public bool? Episode97 { get; set; }
        public bool? Episode98 { get; set; }
        public bool? Episode99 { get; set; }
        public bool? Episode100 { get; set; }
    }
}